### ISSUE TITLE
Pixiv fetch image?

### ISSUE THREAD

**Issue by BobbyWibowo** [tekezo/ImageLnk#1]
Is there anyway to fetch the actual image with this library?
I tried doing:
```php
$url = 'http://www.pixiv.net/member_illust.php?mode=medium&illust_id=37507605';
$imagelnk = ImageLnk::getImageInfo($url);
$links = $imagelnk->getImageURLs(); // I've confirmed that it'll return the image link successfully till this point
$rImageLnk = ImageLnk_Fetcher::fetch($links[0]);
$path = 'some_path_here';
$saveImage = fopen($path, "w");
fwrite($saveImage, $rImageLink->getBody());
fclose($saveImage);
```
to fetch the actual image, hoping that the library will reuse the cookies or something (because I've specified login username and password in advance). But the result was Forbidden request (well, due to the method, the actual error page with forbidden message on it was saved to the file instead, lmao).
Any help please?

**Comment by BobbyWibowo** [comment]
Oh never mind. I had to set the referrer. And just to be safe, I set the referrer as the original page link.
```php
$rImageLnk = ImageLnk_Fetcher::fetch($links[0], $url);
```
And it worked just fine. Thanks for the library!

**Comment by tekezo** [comment]
You are right. The referer is very important in pixiv.
